language: node_js
node_js:
  - "8"
env:
  - TEST_DIR=Server
script: cd $TEST_DIR && npm install
deploy:
  provider: codedeploy
  access_key_id: $AWSAccessKeyId
  secret_access_key: $AWSSecretKey
  revision_type: github
  application: teller-production-application
  deployment_group: teller-production-deployment
  on:
    branch: master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

