version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/teller-install
hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 300
<<<<<<< HEAD
      runas: root
=======
      runas: root
>>>>>>> 67a2d5daf6c42581728a3af45da5f76ec18280fd
